# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestionePrenotazioniView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from Prenotazioni.ViewsPrenotazioni.NuovaPrenotazione1View import NuovaPrenotazione1View
from Prenotazioni.ViewsPrenotazioni.PrenotazioniRegistrateView import PrenotazioniRegistrateView


class GestionePrenotazioniView(object):
    def setupUi(self, Form, app):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutPrincipale = QtWidgets.QVBoxLayout()
        self.verticalLayoutPrincipale.setObjectName("verticalLayoutPrincipale")
        self.horizontalLayoutIndietroLogout = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIndietroLogout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayoutIndietroLogout.setObjectName("horizontalLayoutIndietroLogout")
        self.pushButtonIndietro = QtWidgets.QPushButton(Form)
        self.pushButtonIndietro.setObjectName("pushButtonIndietro")
        self.pushButtonIndietro.clicked.connect(lambda: self.chiudiFinestra(Form))
        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonIndietro)
        self.pushButtonLogout = QtWidgets.QPushButton(Form)
        self.pushButtonLogout.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.pushButtonLogout.clicked.connect(lambda: self.chiudiApp(app))
        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonLogout)
        self.verticalLayoutPrincipale.addLayout(self.horizontalLayoutIndietroLogout)
        self.pushButtonPrenotazioniRegistrate = QtWidgets.QPushButton(Form)
        self.pushButtonPrenotazioniRegistrate.setMinimumSize(QtCore.QSize(0, 270))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonPrenotazioniRegistrate.setFont(font)
        self.pushButtonPrenotazioniRegistrate.setObjectName("pushButtonPrenotazioniRegistrate")
        self.pushButtonPrenotazioniRegistrate.clicked.connect(lambda: self.gestisciPrenotazioniRegistrate(app))

        self.verticalLayoutPrincipale.addWidget(self.pushButtonPrenotazioniRegistrate)
        self.pushButtonNuovaPrenotazione = QtWidgets.QPushButton(Form)
        self.pushButtonNuovaPrenotazione.setMinimumSize(QtCore.QSize(0, 270))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonNuovaPrenotazione.setFont(font)
        self.pushButtonNuovaPrenotazione.setObjectName("pushButtonNuovaPrenotazione")
        self.pushButtonNuovaPrenotazione.clicked.connect(lambda: self.inserisciNuovaPrenotazione(app, Form))
        self.verticalLayoutPrincipale.addWidget(self.pushButtonNuovaPrenotazione)
        self.verticalLayout.addLayout(self.verticalLayoutPrincipale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Segretario - Gestione Prenotazioni"))
        self.pushButtonIndietro.setText(_translate("Form", "INDIETRO"))
        self.pushButtonLogout.setText(_translate("Form", "LOGOUT"))
        self.pushButtonPrenotazioniRegistrate.setText(_translate("Form", "Prenotazioni registrate"))
        self.pushButtonNuovaPrenotazione.setText(_translate("Form", "Nuova prenotazione"))


    def gestisciPrenotazioniRegistrate(self, app):
        self.vistaPrenotazioniRegistrate = QtWidgets.QWidget()
        uivistaPrenotazioniRegistrate = PrenotazioniRegistrateView()
        uivistaPrenotazioniRegistrate.setupUi(self.vistaPrenotazioniRegistrate, app)
        self.vistaPrenotazioniRegistrate.show()

    def inserisciNuovaPrenotazione(self, app, Form):
        self.vistaNuovaPrenotazione1 = QtWidgets.QWidget()
        uivistaNuovaPrenotazione1 = NuovaPrenotazione1View()
        uivistaNuovaPrenotazione1.setupUi(self.vistaNuovaPrenotazione1, app, Form)
        self.vistaNuovaPrenotazione1.show()

    def chiudiFinestra(self,Form):
        Form.close()

    def chiudiApp(self,app):
        sys.exit(app.exec_())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = GestionePrenotazioniView()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
