# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NuovaPrenotazione2View.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class NuovaPrenotazione2View(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutPrincipale = QtWidgets.QVBoxLayout()
        self.verticalLayoutPrincipale.setObjectName("verticalLayoutPrincipale")
        self.horizontalLayoutIndietroLogout = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIndietroLogout.setObjectName("horizontalLayoutIndietroLogout")
        self.pushButtonIndietro = QtWidgets.QPushButton(Form)
        self.pushButtonIndietro.setObjectName("pushButtonIndietro")
        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonIndietro)
        self.pushButtonLogout = QtWidgets.QPushButton(Form)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonLogout)
        self.verticalLayoutPrincipale.addLayout(self.horizontalLayoutIndietroLogout)
        self.labelDomanda = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(15)
        self.labelDomanda.setFont(font)
        self.labelDomanda.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDomanda.setObjectName("labelDomanda")
        self.verticalLayoutPrincipale.addWidget(self.labelDomanda)
        self.pushButtonPrenotazioneTrattamento = QtWidgets.QPushButton(Form)
        self.pushButtonPrenotazioneTrattamento.setMinimumSize(QtCore.QSize(0, 200))
        self.pushButtonPrenotazioneTrattamento.setObjectName("pushButtonPrenotazioneTrattamento")
        self.verticalLayoutPrincipale.addWidget(self.pushButtonPrenotazioneTrattamento)
        self.pushButtonPrenotazioneConsulenza = QtWidgets.QPushButton(Form)
        self.pushButtonPrenotazioneConsulenza.setMinimumSize(QtCore.QSize(0, 200))
        self.pushButtonPrenotazioneConsulenza.setObjectName("pushButtonPrenotazioneConsulenza")
        self.verticalLayoutPrincipale.addWidget(self.pushButtonPrenotazioneConsulenza)
        self.verticalLayout.addLayout(self.verticalLayoutPrincipale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Segretario - Nuova prenotazione - seleziona la tipologia di prenotazione"))
        self.pushButtonIndietro.setText(_translate("Form", "INDIETRO"))
        self.pushButtonLogout.setText(_translate("Form", "LOGOUT"))
        self.labelDomanda.setText(_translate("Form", "Che tipo di prenotazione vuoi registrare?"))
        self.pushButtonPrenotazioneTrattamento.setText(_translate("Form", "Prenotazione di trattamento fisioterapico"))
        self.pushButtonPrenotazioneConsulenza.setText(_translate("Form", "Prenotazione di Consulenza Medica"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = NuovaPrenotazione2View()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
