# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NuovaPrenotazione1View.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutPrincipale = QtWidgets.QVBoxLayout()
        self.verticalLayoutPrincipale.setObjectName("verticalLayoutPrincipale")
        self.horizontalLayoutIndietroLogout = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIndietroLogout.setObjectName("horizontalLayoutIndietroLogout")
        self.pushButtonIndietro = QtWidgets.QPushButton(Form)
        self.pushButtonIndietro.setObjectName("pushButtonIndietro")
        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonIndietro)
        self.pushButtonLogout = QtWidgets.QPushButton(Form)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonLogout)
        self.verticalLayoutPrincipale.addLayout(self.horizontalLayoutIndietroLogout)
        self.labelDomandaSceglPaziente = QtWidgets.QLabel(Form)
        self.labelDomandaSceglPaziente.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelDomandaSceglPaziente.setFont(font)
        self.labelDomandaSceglPaziente.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDomandaSceglPaziente.setObjectName("labelDomandaSceglPaziente")
        self.verticalLayoutPrincipale.addWidget(self.labelDomandaSceglPaziente)
        self.gridLayoutRicerca = QtWidgets.QGridLayout()
        self.gridLayoutRicerca.setObjectName("gridLayoutRicerca")
        self.lineEditRicercaCodiceFiscale = QtWidgets.QLineEdit(Form)
        self.lineEditRicercaCodiceFiscale.setObjectName("lineEditRicercaCodiceFiscale")
        self.gridLayoutRicerca.addWidget(self.lineEditRicercaCodiceFiscale, 3, 1, 1, 1)
        self.labelRicercaCognome = QtWidgets.QLabel(Form)
        self.labelRicercaCognome.setObjectName("labelRicercaCognome")
        self.gridLayoutRicerca.addWidget(self.labelRicercaCognome, 2, 0, 1, 1)
        self.labelRicercaNome = QtWidgets.QLabel(Form)
        self.labelRicercaNome.setObjectName("labelRicercaNome")
        self.gridLayoutRicerca.addWidget(self.labelRicercaNome, 1, 0, 1, 1)
        self.pushButtonRicerca = QtWidgets.QPushButton(Form)
        self.pushButtonRicerca.setObjectName("pushButtonRicerca")
        self.gridLayoutRicerca.addWidget(self.pushButtonRicerca, 7, 0, 1, 2)
        self.lineEditRicercaNome = QtWidgets.QLineEdit(Form)
        self.lineEditRicercaNome.setObjectName("lineEditRicercaNome")
        self.gridLayoutRicerca.addWidget(self.lineEditRicercaNome, 1, 1, 1, 1)
        self.lineEditRicercaCognome = QtWidgets.QLineEdit(Form)
        self.lineEditRicercaCognome.setObjectName("lineEditRicercaCognome")
        self.gridLayoutRicerca.addWidget(self.lineEditRicercaCognome, 2, 1, 1, 1)
        self.labelRicercaCodiceFiscale = QtWidgets.QLabel(Form)
        self.labelRicercaCodiceFiscale.setObjectName("labelRicercaCodiceFiscale")
        self.gridLayoutRicerca.addWidget(self.labelRicercaCodiceFiscale, 3, 0, 1, 1)
        self.verticalLayoutPrincipale.addLayout(self.gridLayoutRicerca)
        self.listViewPrenotazioni = QtWidgets.QListView(Form)
        self.listViewPrenotazioni.setObjectName("listViewPrenotazioni")
        self.verticalLayoutPrincipale.addWidget(self.listViewPrenotazioni)
        self.verticalLayputVisualizzaPrenotazione = QtWidgets.QVBoxLayout()
        self.verticalLayputVisualizzaPrenotazione.setObjectName("verticalLayputVisualizzaPrenotazione")
        self.pushButtonSelezionaPaziente = QtWidgets.QPushButton(Form)
        self.pushButtonSelezionaPaziente.setObjectName("pushButtonSelezionaPaziente")
        self.verticalLayputVisualizzaPrenotazione.addWidget(self.pushButtonSelezionaPaziente)
        self.verticalLayoutPrincipale.addLayout(self.verticalLayputVisualizzaPrenotazione)
        self.verticalLayout.addLayout(self.verticalLayoutPrincipale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Segretario - Nuova prenotazione - Seleziona un paziente"))
        self.pushButtonIndietro.setText(_translate("Form", "INDIETRO"))
        self.pushButtonLogout.setText(_translate("Form", "LOGOUT"))
        self.labelDomandaSceglPaziente.setText(_translate("Form", "Per quale paziente vuoi registrare una nuova prenotazione?"))
        self.labelRicercaCognome.setText(_translate("Form", "Ricerca per cognome paziente:"))
        self.labelRicercaNome.setText(_translate("Form", "Ricerca per nome paziente: "))
        self.pushButtonRicerca.setText(_translate("Form", "Ricerca"))
        self.labelRicercaCodiceFiscale.setText(_translate("Form", "Ricerca per codice fiscale paziente:"))
        self.pushButtonSelezionaPaziente.setText(_translate("Form", "Seleziona paziente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
