# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PrenotazioniRegistrateView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PrenotazioniRegistrateView(object):
    def setupUi(self, Form, app):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutPrincipale = QtWidgets.QVBoxLayout()
        self.verticalLayoutPrincipale.setObjectName("verticalLayoutPrincipale")
        self.horizontalLayoutIndietroLogout = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIndietroLogout.setObjectName("horizontalLayoutIndietroLogout")
        self.pushButtonIndietro = QtWidgets.QPushButton(Form)
        self.pushButtonIndietro.setObjectName("pushButtonIndietro")
        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonIndietro)
        self.pushButtonLogout = QtWidgets.QPushButton(Form)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonLogout)
        self.verticalLayoutPrincipale.addLayout(self.horizontalLayoutIndietroLogout)
        self.gridLayoutRicerca = QtWidgets.QGridLayout()
        self.gridLayoutRicerca.setObjectName("gridLayoutRicerca")
        self.labelRicercaCognome = QtWidgets.QLabel(Form)
        self.labelRicercaCognome.setObjectName("labelRicercaCognome")
        self.gridLayoutRicerca.addWidget(self.labelRicercaCognome, 3, 0, 1, 1)
        self.dateEditDataFine = QtWidgets.QDateEdit(Form)
        self.dateEditDataFine.setObjectName("dateEditDataFine")
        self.gridLayoutRicerca.addWidget(self.dateEditDataFine, 6, 1, 1, 1)
        self.labelRicercaDataFine = QtWidgets.QLabel(Form)
        self.labelRicercaDataFine.setObjectName("labelRicercaDataFine")
        self.gridLayoutRicerca.addWidget(self.labelRicercaDataFine, 6, 0, 1, 1)
        self.labelRicercaNome = QtWidgets.QLabel(Form)
        self.labelRicercaNome.setObjectName("labelRicercaNome")
        self.gridLayoutRicerca.addWidget(self.labelRicercaNome, 2, 0, 1, 1)
        self.lineEditRicercaNome = QtWidgets.QLineEdit(Form)
        self.lineEditRicercaNome.setObjectName("lineEditRicercaNome")
        self.gridLayoutRicerca.addWidget(self.lineEditRicercaNome, 2, 1, 1, 1)
        self.comboBoxTipologiaPrenotazione = QtWidgets.QComboBox(Form)
        self.comboBoxTipologiaPrenotazione.setObjectName("comboBoxTipologiaPrenotazione")
        self.gridLayoutRicerca.addWidget(self.comboBoxTipologiaPrenotazione, 1, 1, 1, 1)
        self.pushButtonRicerca = QtWidgets.QPushButton(Form)
        self.pushButtonRicerca.setObjectName("pushButtonRicerca")
        self.gridLayoutRicerca.addWidget(self.pushButtonRicerca, 10, 0, 1, 2)
        self.dateEditDataInizio = QtWidgets.QDateEdit(Form)
        self.dateEditDataInizio.setObjectName("dateEditDataInizio")
        self.gridLayoutRicerca.addWidget(self.dateEditDataInizio, 5, 1, 1, 1)
        self.labelRicercaPrenotazioneTipo = QtWidgets.QLabel(Form)
        self.labelRicercaPrenotazioneTipo.setObjectName("labelRicercaPrenotazioneTipo")
        self.gridLayoutRicerca.addWidget(self.labelRicercaPrenotazioneTipo, 1, 0, 1, 1)
        self.lineEditRicercaCognome = QtWidgets.QLineEdit(Form)
        self.lineEditRicercaCognome.setObjectName("lineEditRicercaCognome")
        self.gridLayoutRicerca.addWidget(self.lineEditRicercaCognome, 3, 1, 1, 1)
        self.labelRicercaDataInizio = QtWidgets.QLabel(Form)
        self.labelRicercaDataInizio.setObjectName("labelRicercaDataInizio")
        self.gridLayoutRicerca.addWidget(self.labelRicercaDataInizio, 5, 0, 1, 1)
        self.labelRicercaCodiceFiscale = QtWidgets.QLabel(Form)
        self.labelRicercaCodiceFiscale.setObjectName("labelRicercaCodiceFiscale")
        self.gridLayoutRicerca.addWidget(self.labelRicercaCodiceFiscale, 4, 0, 1, 1)
        self.lineEditRicercaCodiceFiscale = QtWidgets.QLineEdit(Form)
        self.lineEditRicercaCodiceFiscale.setObjectName("lineEditRicercaCodiceFiscale")
        self.gridLayoutRicerca.addWidget(self.lineEditRicercaCodiceFiscale, 4, 1, 1, 1)
        self.verticalLayoutPrincipale.addLayout(self.gridLayoutRicerca)
        self.listViewPrenotazioni = QtWidgets.QListView(Form)
        self.listViewPrenotazioni.setObjectName("listViewPrenotazioni")
        self.verticalLayoutPrincipale.addWidget(self.listViewPrenotazioni)
        self.verticalLayputVisualizzaPrenotazione = QtWidgets.QVBoxLayout()
        self.verticalLayputVisualizzaPrenotazione.setObjectName("verticalLayputVisualizzaPrenotazione")
        self.pushButtonVisualizzaPrenotazione = QtWidgets.QPushButton(Form)
        self.pushButtonVisualizzaPrenotazione.setObjectName("pushButtonVisualizzaPrenotazione")
        self.verticalLayputVisualizzaPrenotazione.addWidget(self.pushButtonVisualizzaPrenotazione)
        self.verticalLayoutPrincipale.addLayout(self.verticalLayputVisualizzaPrenotazione)
        self.verticalLayout.addLayout(self.verticalLayoutPrincipale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Segretario - Prenotazioni registrate"))
        self.pushButtonIndietro.setText(_translate("Form", "INDIETRO"))
        self.pushButtonLogout.setText(_translate("Form", "LOGOUT"))
        self.labelRicercaCognome.setText(_translate("Form", "Ricerca per cognome paziente:"))
        self.labelRicercaDataFine.setText(_translate("Form", "Ricerca per prenotazioni entro la data:"))
        self.labelRicercaNome.setText(_translate("Form", "Ricerca per nome paziente: "))
        self.pushButtonRicerca.setText(_translate("Form", "Ricerca"))
        self.labelRicercaPrenotazioneTipo.setText(_translate("Form", "Ricerca per tipologia prenotazione:"))
        self.labelRicercaDataInizio.setText(_translate("Form", "Ricerca per prenotazioni dalla data:"))
        self.labelRicercaCodiceFiscale.setText(_translate("Form", "Ricerca per codice fiscale paziente:"))
        self.pushButtonVisualizzaPrenotazione.setText(_translate("Form", "Visualizza prenotazione"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = PrenotazioniRegistrateView()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
