# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestioneTrattConsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem

from TrattamentiConsulenze.ControllersTrattCons.ElencoTrattamentiController import ElencoTrattamentiController
from TrattamentiConsulenze.ViewsTrattCons.VisualizzaTrattView import VisualizzaTrattView


class GestioneTrattConsView(object):

    def __init__(self):
        self.trattamenti = None
        self.vistaTrattamento = None
        self.app = None

    def setupUi(self, Form, app):
        self.app = app

        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutPrincipale = QtWidgets.QVBoxLayout()
        self.verticalLayoutPrincipale.setObjectName("verticalLayoutPrincipale")
        self.horizontalLayoutIndietroLogout = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIndietroLogout.setObjectName("horizontalLayoutIndietroLogout")

        self.pushButtonIndietro = QtWidgets.QPushButton(Form)
        self.pushButtonIndietro.setObjectName("pushButtonIndietro")
        self.pushButtonIndietro.clicked.connect(lambda: self.chiudiFinestra(Form))

        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonIndietro)

        self.pushButtonLogout = QtWidgets.QPushButton(Form)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.pushButtonLogout.clicked.connect(lambda: self.chiudiApp(app))

        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonLogout)
        self.verticalLayoutPrincipale.addLayout(self.horizontalLayoutIndietroLogout)
        self.gridLayoutRicerca = QtWidgets.QGridLayout()
        self.gridLayoutRicerca.setObjectName("gridLayoutRicerca")
        self.labelRicercaTraNome = QtWidgets.QLabel(Form)
        self.labelRicercaTraNome.setObjectName("labelRicercaTraNome")
        self.gridLayoutRicerca.addWidget(self.labelRicercaTraNome, 2, 0, 1, 1)

        self.comboBoxClasseTra = QtWidgets.QComboBox(Form)
        self.comboBoxClasseTra.setObjectName("comboBoxClasseTra")
        self.comboBoxClasseTra.addItems(["Tutte","Fisio estetica", "Fisioterapia strumentale", "Fisioterapia manuale",
                                      "Fisioterapia posturale", "Fisioterapia neurologica",
                                      "Riabilitazione sportiva e performance",
                                      "Idrokinesiterapia", "Realtà virtuale"])

        self.gridLayoutRicerca.addWidget(self.comboBoxClasseTra, 1, 1, 1, 1)
        self.labelRicercaTraClasse = QtWidgets.QLabel(Form)
        self.labelRicercaTraClasse.setObjectName("labelRicercaTraClasse")
        self.gridLayoutRicerca.addWidget(self.labelRicercaTraClasse, 1, 0, 1, 1)
        self.lineEditNomeTra = QtWidgets.QLineEdit(Form)
        self.lineEditNomeTra.setObjectName("lineEditNomeTra")
        self.gridLayoutRicerca.addWidget(self.lineEditNomeTra, 2, 1, 1, 1)

        self.pushButtonRicerca = QtWidgets.QPushButton(Form)
        self.pushButtonRicerca.setObjectName("pushButtonRicerca")
        self.pushButtonRicerca.clicked.connect(self.ricercaTrattamento)

        self.gridLayoutRicerca.addWidget(self.pushButtonRicerca, 9, 0, 1, 2)
        self.verticalLayoutPrincipale.addLayout(self.gridLayoutRicerca)

        self.listViewTrattamenti = QtWidgets.QListView(Form)
        self.listViewTrattamenti.setObjectName("listViewTrattamenti")

        self.verticalLayoutPrincipale.addWidget(self.listViewTrattamenti)
        self.verticalLayoutNuovoTraGestisciCons = QtWidgets.QVBoxLayout()
        self.verticalLayoutNuovoTraGestisciCons.setObjectName("verticalLayoutNuovoTraGestisciCons")

        self.pushButtonVisualizzaTrattamento = QtWidgets.QPushButton(Form)
        self.pushButtonVisualizzaTrattamento.setObjectName("pushButtonVisualizzaTrattamento")
        self.pushButtonVisualizzaTrattamento.clicked.connect(self.visualizzaTrattamentoSelezionato)

        self.verticalLayoutNuovoTraGestisciCons.addWidget(self.pushButtonVisualizzaTrattamento)
        self.pushButtonNuovoTra = QtWidgets.QPushButton(Form)
        self.pushButtonNuovoTra.setObjectName("pushButtonNuovoTra")
        self.verticalLayoutNuovoTraGestisciCons.addWidget(self.pushButtonNuovoTra)
        self.pushButtonGestisciCons = QtWidgets.QPushButton(Form)
        self.pushButtonGestisciCons.setObjectName("pushButtonGestisciCons")
        self.verticalLayoutNuovoTraGestisciCons.addWidget(self.pushButtonGestisciCons)
        self.verticalLayoutPrincipale.addLayout(self.verticalLayoutNuovoTraGestisciCons)
        self.verticalLayout.addLayout(self.verticalLayoutPrincipale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.visualizzaListaTrattamenti()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Amministratore"))
        self.pushButtonIndietro.setText(_translate("Form", "INDIETRO"))
        self.pushButtonLogout.setText(_translate("Form", "LOGOUT"))
        self.labelRicercaTraNome.setText(_translate("Form", "Ricerca per nome trattamento: "))
        self.labelRicercaTraClasse.setText(_translate("Form", "Ricerca per classe trattamento:"))
        self.pushButtonRicerca.setText(_translate("Form", "Ricerca"))
        self.pushButtonVisualizzaTrattamento.setText(_translate("Form", "Visualizza trattamento selezionato"))
        self.pushButtonNuovoTra.setText(_translate("Form", "Nuovo Trattamento Fisioterapico"))
        self.pushButtonGestisciCons.setText(_translate("Form", "Gestisci Consulenza medica"))


    def visualizzaListaTrattamenti(self):
        self.trattamenti = ElencoTrattamentiController().getElencoTrattamenti()
        listview_model = QStandardItemModel(self.listViewTrattamenti)
        for trattamento in self.trattamenti.values():
            item = QStandardItem()
            etichetta = f"{trattamento.nome} : {trattamento.classe} - {trattamento.codiceTrattamento}"
            item.setText(etichetta)
            item.setEditable(False)
            font = item.font()
            font.setPointSize(16)
            item.setFont(font)
            listview_model.appendRow(item)
        self.listViewTrattamenti.setModel(listview_model)

    def visualizzaTrattamentoSelezionato(self):

            trattamentoSelezionato = self.listViewTrattamenti.selectedIndexes()[0].data()
            codiceTrattamento = int(trattamentoSelezionato.split("-")[1].strip())
            dictParametri = {}
            dictParametri["codiceTrattamento"] = codiceTrattamento
            trattamento = ElencoTrattamentiController().ricercaTrattamento(dictParametri)

            self.vistaTrattamento = QtWidgets.QWidget()
            uiVistaTrattamento = VisualizzaTrattView(trattamento[codiceTrattamento], self.visualizzaListaTrattamenti, self.app)
            uiVistaTrattamento.setupUi(self.vistaTrattamento)
            self.vistaTrattamento.show()

    def ricercaTrattamento(self):
        dictParametri={}
        dictParametri["classe"]=str(self.comboBoxClasseTra.currentText())
        dictParametri["nome"]=str(self.lineEditNomeTra.text()).strip()
        if str(self.comboBoxClasseTra.currentText())=="Tutte":
            dictParametri["classe"]=""
        self.trattamentiRisultato=ElencoTrattamentiController().ricercaTrattamento(dictParametri)

        listview_model = QStandardItemModel(self.listViewTrattamenti)
        for trattamento in self.trattamentiRisultato.values():
            item = QStandardItem()
            etichetta = f"{trattamento.nome} : {trattamento.classe} - {trattamento.codiceTrattamento}"
            item.setText(etichetta)
            item.setEditable(False)
            font = item.font()
            font.setPointSize(16)
            item.setFont(font)
            listview_model.appendRow(item)
        self.listViewTrattamenti.setModel(listview_model)

    def chiudiFinestra(self,Form):
        Form.close()

    def chiudiApp(self,app):
        sys.exit(app.exec_())


"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = GestioneTrattConsView()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
"""