# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModificaTrattView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

#from TrattamentiConsulenze.ControllersTrattCons.ElencoTrattamentiController import ElencoTrattamentiController
from TrattamentiConsulenze.ControllersTrattCons.TrattamentoController import TrattamentoController


class ModificaTrattView(object):

    def __init__(self , trattamento, aggiornaListaTrattamenti):
        self.trattamento = trattamento
        self.aggiornaListaTrattamenti = aggiornaListaTrattamenti

    def setupUi(self, Form, app):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutPrincipale = QtWidgets.QVBoxLayout()
        self.verticalLayoutPrincipale.setObjectName("verticalLayoutPrincipale")
        self.horizontalLayoutIndietroLogout = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIndietroLogout.setObjectName("horizontalLayoutIndietroLogout")

        self.pushButtonIndietro = QtWidgets.QPushButton(Form)
        self.pushButtonIndietro.setObjectName("pushButtonIndietro")
        self.pushButtonIndietro.clicked.connect(lambda: self.chiudiFinestra(Form))

        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonIndietro)
        self.pushButtonLogout = QtWidgets.QPushButton(Form)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.pushButtonLogout.clicked.connect(lambda: self.chiudiApp(app))

        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonLogout)
        self.verticalLayoutPrincipale.addLayout(self.horizontalLayoutIndietroLogout)
        self.labelDettagliTrattamento = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelDettagliTrattamento.setFont(font)
        self.labelDettagliTrattamento.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDettagliTrattamento.setObjectName("labelDettagliTrattamento")
        self.verticalLayoutPrincipale.addWidget(self.labelDettagliTrattamento)
        self.verticalLayoutDatiTrattamento = QtWidgets.QVBoxLayout()
        self.verticalLayoutDatiTrattamento.setObjectName("verticalLayoutDatiTrattamento")
        self.horizontalLayoutNome = QtWidgets.QHBoxLayout()
        self.horizontalLayoutNome.setObjectName("horizontalLayoutNome")
        self.labelNome = QtWidgets.QLabel(Form)
        self.labelNome.setObjectName("labelNome")
        self.horizontalLayoutNome.addWidget(self.labelNome)

        self.lineEditNome = QtWidgets.QLineEdit(Form)
        self.lineEditNome.setObjectName("lineEditNome")
        self.lineEditNome.setText(str(self.trattamento.nome))

        self.horizontalLayoutNome.addWidget(self.lineEditNome)
        self.verticalLayoutDatiTrattamento.addLayout(self.horizontalLayoutNome)
        self.horizontalLayoutClasse = QtWidgets.QHBoxLayout()
        self.horizontalLayoutClasse.setObjectName("horizontalLayoutClasse")
        self.labelClasse = QtWidgets.QLabel(Form)
        self.labelClasse.setMaximumSize(QtCore.QSize(38, 16777215))
        self.labelClasse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelClasse.setObjectName("labelClasse")
        self.horizontalLayoutClasse.addWidget(self.labelClasse)

        self.comboBoxClasse = QtWidgets.QComboBox(Form)
        self.comboBoxClasse.setObjectName("comboBoxClasse")
        self.comboBoxClasse.addItems(["Fisio estetica", "Fisioterapia strumentale", "Fisioterapia manuale",
                                         "Fisioterapia posturale", "Fisioterapia neurologica",
                                         "Riabilitazione sportiva e performance",
                                         "Idrokinesiterapia", "Realtà virtuale"])
        self.comboBoxClasse.setCurrentText(str(self.trattamento.classe))


        self.horizontalLayoutClasse.addWidget(self.comboBoxClasse)
        self.verticalLayoutDatiTrattamento.addLayout(self.horizontalLayoutClasse)
        self.horizontalLayoutCosto = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCosto.setObjectName("horizontalLayoutCosto")
        self.labelCosto = QtWidgets.QLabel(Form)
        self.labelCosto.setObjectName("labelCosto")
        self.horizontalLayoutCosto.addWidget(self.labelCosto)

        self.lineEditCosto = QtWidgets.QLineEdit(Form)
        self.lineEditCosto.setObjectName("lineEditCosto")
        self.lineEditCosto.setText(str(self.trattamento.costo))

        self.horizontalLayoutCosto.addWidget(self.lineEditCosto)
        self.labelEuro = QtWidgets.QLabel(Form)
        self.labelEuro.setObjectName("labelEuro")
        self.horizontalLayoutCosto.addWidget(self.labelEuro)
        self.verticalLayoutDatiTrattamento.addLayout(self.horizontalLayoutCosto)
        self.horizontalLayoutDurata = QtWidgets.QHBoxLayout()
        self.horizontalLayoutDurata.setObjectName("horizontalLayoutDurata")
        self.labelDurata = QtWidgets.QLabel(Form)
        self.labelDurata.setObjectName("labelDurata")
        self.horizontalLayoutDurata.addWidget(self.labelDurata)

        self.lineEditDurata = QtWidgets.QLineEdit(Form)
        self.lineEditDurata.setObjectName("lineEditDurata")
        self.lineEditDurata.setText(str(self.trattamento.durata))

        self.horizontalLayoutDurata.addWidget(self.lineEditDurata)
        self.labelMinuti = QtWidgets.QLabel(Form)
        self.labelMinuti.setObjectName("labelMinuti")
        self.horizontalLayoutDurata.addWidget(self.labelMinuti)
        self.verticalLayoutDatiTrattamento.addLayout(self.horizontalLayoutDurata)
        self.verticalLayoutPrincipale.addLayout(self.verticalLayoutDatiTrattamento)
        spacerItem = QtWidgets.QSpacerItem(40, 350, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayoutPrincipale.addItem(spacerItem)

        self.pushButtonSalva = QtWidgets.QPushButton(Form)
        self.pushButtonSalva.setObjectName("pushButtonSalva")
        self.pushButtonSalva.clicked.connect(lambda: self.salvaModificaTrattamento(Form))

        self.verticalLayoutPrincipale.addWidget(self.pushButtonSalva)
        self.verticalLayout.addLayout(self.verticalLayoutPrincipale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Amministratore - modifica trattamento"))
        self.pushButtonIndietro.setText(_translate("Form", "INDIETRO"))
        self.pushButtonLogout.setText(_translate("Form", "LOGOUT"))
        self.labelDettagliTrattamento.setText(_translate("Form", "Dettagli trattamento:"))
        self.labelNome.setText(_translate("Form", "Nome:"))
        self.labelClasse.setText(_translate("Form", "Classe:"))
        self.labelCosto.setText(_translate("Form", "Costo:"))
        self.labelEuro.setText(_translate("Form", "€"))
        self.labelDurata.setText(_translate("Form", "Durata:"))
        self.labelMinuti.setText(_translate("Form", "minuti"))
        self.pushButtonSalva.setText(_translate("Form", "Salva"))

    def salvaModificaTrattamento(self, Form):
        if TrattamentoController().modificaTrattamento(self.trattamento, str(self.lineEditNome.text()).strip(), str(self.comboBoxClasse.currentText()),
                                                     str(self.lineEditCosto.text()).strip(), str(self.lineEditDurata.text().strip())):
            self.chiudiFinestra(Form) #chiudendosi la finestra viene mostrata nuovamente la finestra di gestione dei trattamenti che stava sotto
            self.aggiornaListaTrattamenti() #la finestra della lista dei trattamenti si deve aggiornare per far comparire il trattamento appena aggiunto

        else:
            errore = QMessageBox()
            errore.setWindowTitle("Errore di inserimento")
            errore.setText("Controlla che siano stati compilati tutti i campi e che nei campi 'costo' o 'durata' siano stati inseriti dei valori numerici.")
            errore.setIcon(QMessageBox.Warning)
            errore.setStandardButtons(QMessageBox.Ok)
            errore.exec_()

    def chiudiFinestra(self, Form):
        Form.close()

    def chiudiApp(self, app):
        sys.exit(app.exec_())

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = ModificaTrattView()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
"""
