# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualizzaTrattView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from TrattamentiConsulenze.ControllersTrattCons.TrattamentoController import TrattamentoController
from TrattamentiConsulenze.ViewsTrattCons.ModificaTrattView import ModificaTrattView


class VisualizzaTrattView(object):

    def __init__(self , trattamento, aggiornaListaTrattamenti):
        self.trattamento = trattamento
        self.aggiornaListaTrattamenti = aggiornaListaTrattamenti

    def setupUi(self, Form, app):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutPrincipale = QtWidgets.QVBoxLayout()
        self.verticalLayoutPrincipale.setObjectName("verticalLayoutPrincipale")
        self.horizontalLayoutIndietroLogout = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIndietroLogout.setObjectName("horizontalLayoutIndietroLogout")

        self.pushButtonIndietro = QtWidgets.QPushButton(Form)
        self.pushButtonIndietro.setObjectName("pushButtonIndietro")
        self.pushButtonIndietro.clicked.connect(lambda: self.chiudiFinestra(Form))

        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonIndietro)
        self.pushButtonLogout = QtWidgets.QPushButton(Form)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.pushButtonLogout.clicked.connect(lambda: self.chiudiApp(app))

        self.horizontalLayoutIndietroLogout.addWidget(self.pushButtonLogout)
        self.verticalLayoutPrincipale.addLayout(self.horizontalLayoutIndietroLogout)
        self.labelDettagliTrattamento = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelDettagliTrattamento.setFont(font)
        self.labelDettagliTrattamento.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDettagliTrattamento.setObjectName("labelDettagliTrattamento")
        self.verticalLayoutPrincipale.addWidget(self.labelDettagliTrattamento)
        self.verticalLayoutDatiTrattamento = QtWidgets.QVBoxLayout()
        self.verticalLayoutDatiTrattamento.setObjectName("verticalLayoutDatiTrattamento")
        self.horizontalLayoutNome = QtWidgets.QHBoxLayout()
        self.horizontalLayoutNome.setObjectName("horizontalLayoutNome")
        self.labelNome = QtWidgets.QLabel(Form)
        self.labelNome.setObjectName("labelNome")
        self.labelNome.setMaximumWidth(40)
        self.horizontalLayoutNome.addWidget(self.labelNome)

        self.labelNomeValue = QtWidgets.QLabel(Form)
        self.labelNomeValue.setText(str(self.trattamento.nome))
        self.labelNomeValue.setObjectName("labelNomeValue")


        self.horizontalLayoutNome.addWidget(self.labelNomeValue)
        self.verticalLayoutDatiTrattamento.addLayout(self.horizontalLayoutNome)
        self.horizontalLayoutClasse = QtWidgets.QHBoxLayout()
        self.horizontalLayoutClasse.setObjectName("horizontalLayoutClasse")
        self.labelClasse = QtWidgets.QLabel(Form)
        self.labelClasse.setObjectName("labelClasse")
        self.labelClasse.setMaximumWidth(40)
        self.horizontalLayoutClasse.addWidget(self.labelClasse)

        self.labelClasseValue = QtWidgets.QLabel(Form)
        self.labelClasseValue.setText(str(self.trattamento.classe))
        self.labelClasseValue.setObjectName("labelClasseValue")

        self.horizontalLayoutClasse.addWidget(self.labelClasseValue)
        self.verticalLayoutDatiTrattamento.addLayout(self.horizontalLayoutClasse)
        self.horizontalLayoutCosto = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCosto.setObjectName("horizontalLayoutCosto")
        self.labelCosto = QtWidgets.QLabel(Form)
        self.labelCosto.setObjectName("labelCosto")
        self.labelCosto.setMaximumWidth(40)
        self.horizontalLayoutCosto.addWidget(self.labelCosto)

        self.labelCostoValue = QtWidgets.QLabel(Form)
        self.labelCostoValue.setText(str(self.trattamento.costo))
        self.labelCostoValue.setObjectName("labelCostoValue")
        self.labelCostoValue.setMaximumWidth(20)

        self.horizontalLayoutCosto.addWidget(self.labelCostoValue)
        self.labelEuro = QtWidgets.QLabel(Form)
        self.labelEuro.setObjectName("labelEuro")
        self.horizontalLayoutCosto.addWidget(self.labelEuro)
        self.verticalLayoutDatiTrattamento.addLayout(self.horizontalLayoutCosto)
        self.horizontalLayoutDurata = QtWidgets.QHBoxLayout()
        self.horizontalLayoutDurata.setObjectName("horizontalLayoutDurata")
        self.labelDurata = QtWidgets.QLabel(Form)
        self.labelDurata.setObjectName("labelDurata")
        self.labelDurata.setMaximumWidth(40)
        self.horizontalLayoutDurata.addWidget(self.labelDurata)

        self.labelDurataValue = QtWidgets.QLabel(Form)
        self.labelDurataValue.setText(str(self.trattamento.durata))
        self.labelDurataValue.setObjectName("labelDurataValue")
        self.labelDurataValue.setMaximumWidth(20)

        self.horizontalLayoutDurata.addWidget(self.labelDurataValue)
        self.labelMinuti = QtWidgets.QLabel(Form)
        self.labelMinuti.setObjectName("labelMinuti")
        self.horizontalLayoutDurata.addWidget(self.labelMinuti)
        self.verticalLayoutDatiTrattamento.addLayout(self.horizontalLayoutDurata)
        self.verticalLayoutPrincipale.addLayout(self.verticalLayoutDatiTrattamento)
        self.horizontalLayoutEliminaModificaTra = QtWidgets.QHBoxLayout()
        self.horizontalLayoutEliminaModificaTra.setObjectName("horizontalLayoutEliminaModificaTra")
        self.pushButtonEliminaTra = QtWidgets.QPushButton(Form)

        self.pushButtonEliminaTra.setObjectName("pushButtonEliminaTra")
        self.horizontalLayoutEliminaModificaTra.addWidget(self.pushButtonEliminaTra)
        self.pushButtonEliminaTra.clicked.connect(lambda: self.eliminaTrattamento(Form))

        self.pushButtonModificaTra = QtWidgets.QPushButton(Form)
        self.pushButtonModificaTra.setObjectName("pushButtonModificaTra")
        self.pushButtonModificaTra.clicked.connect(lambda: self.modificaTrattamento(Form, app))

        self.horizontalLayoutEliminaModificaTra.addWidget(self.pushButtonModificaTra)
        self.verticalLayoutPrincipale.addLayout(self.horizontalLayoutEliminaModificaTra)
        self.verticalLayout_2.addLayout(self.verticalLayoutPrincipale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Amministratore - visualizza trattamento"))
        self.pushButtonIndietro.setText(_translate("Form", "INDIETRO"))
        self.pushButtonLogout.setText(_translate("Form", "LOGOUT"))
        self.labelDettagliTrattamento.setText(_translate("Form", "Dettagli trattamento:"))
        self.labelNome.setText(_translate("Form", "Nome:"))
        self.labelClasse.setText(_translate("Form", "Classe:"))
        self.labelCosto.setText(_translate("Form", "Costo:"))
        self.labelEuro.setText(_translate("Form", "€"))
        self.labelDurata.setText(_translate("Form", "Durata:"))
        self.labelMinuti.setText(_translate("Form", "minuti"))
        self.pushButtonEliminaTra.setText(_translate("Form", "Elimina trattamento"))
        self.pushButtonModificaTra.setText(_translate("Form", "Modifica trattamento"))

    def modificaTrattamento(self, Form, app):
        self.vistaModificaTrattamento = QtWidgets.QWidget()
        uivistaModificaTrattamento = ModificaTrattView(self.trattamento, self.aggiornaListaTrattamenti)
        uivistaModificaTrattamento.setupUi(self.vistaModificaTrattamento, app)
        self.vistaModificaTrattamento.show()
        self.chiudiFinestra(Form)

    def eliminaTrattamento(self, Form):
        popupConferma = QMessageBox()
        popupConferma.setText("Sei sicuro di voler eliminare il trattamento visualizzato?")
        popupConferma.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        popupConferma.setWindowTitle("Conferma eliminazione trattamento")
        risposta = popupConferma.exec_()
        if risposta == QMessageBox.Ok:
            TrattamentoController().eliminaTrattamento(self.trattamento)
            self.aggiornaListaTrattamenti()
            self.chiudiFinestra(Form)

    def chiudiFinestra(self, Form):
        Form.close()

    def chiudiApp(self, app):
        sys.exit(app.exec_())

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = VisualizzaTrattView()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
"""
